// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ReactiveOperators")]
[assembly: AssemblyProductAttribute("ReactiveOperators")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.2.2")]
[assembly: AssemblyFileVersionAttribute("1.0.2.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.2.2";
    }
}
